runtime: python37



# [START gae_python_mysql_env]
env_variables:
        CLOUD_SQL_USERNAME: root
        CLOUD_SQL_PASSWORD: Sha1987!
        CLOUD_SQL_DATABASE_NAME: Cloud_6331_DB
        CLOUD_SQL_CONNECTION_NAME: aiman-abdullah-2426:us-central1:aa-2426
        GAE_ENV: standard
# [END gae_python_mysql_env]


readiness_check:
  app_start_timeout_sec: 600


